'use client'

import { useState } from 'react'
import { ChevronDown, Network } from 'lucide-react'
import { Toggle } from '@/components/ui'
import type { Project } from '@prisma/client'
import styles from '../ProjectForm.module.css'

type FormData = Omit<Project, 'id' | 'userId' | 'createdAt' | 'updatedAt' | 'user'>

interface TrafficCaptureSectionProps {
  data: FormData
  updateField: <K extends keyof FormData>(field: K, value: FormData[K]) => void
}

// Phase 0 of the mitmproxy integration: turning this on makes recon retain the
// full httpx response bodies (otherwise discarded after fingerprinting) and
// persist every probed transaction to the Traffic table, viewable at /traffic.
// Off by default: no bodies retained, nothing written.
export function TrafficCaptureSection({ data, updateField }: TrafficCaptureSectionProps) {
  const [isOpen, setIsOpen] = useState(false)
  const enabled = !!data.captureProxyEnabled

  return (
    <div className={styles.section}>
      <div className={styles.sectionHeader} onClick={() => setIsOpen(!isOpen)}>
        <h2 className={styles.sectionTitle}>
          <Network size={16} />
          TrafficMind
          {enabled && <span className={styles.badgeActive}>Active</span>}
        </h2>
        <div className={styles.sectionHeaderRight}>
          <div onClick={(e) => e.stopPropagation()}>
            <Toggle
              checked={enabled}
              onChange={(checked) => updateField('captureProxyEnabled', checked)}
            />
          </div>
          <ChevronDown
            size={16}
            className={`${styles.sectionIcon} ${isOpen ? styles.sectionIconOpen : ''}`}
          />
        </div>
      </div>

      {isOpen && (
        <div className={styles.sectionContent}>
          <p className={styles.sectionDescription}>
            Persist the full request/response of every HTTP transaction generated by
            recon (starting with httpx probes, whose bodies are otherwise discarded
            after fingerprinting) into a queryable TrafficMind store, tagged with its
            source scan run. Browse it under the <strong>TrafficMind</strong> tab.
            Off by default; enabling it retains response bodies (capped) in the
            database, so leave it off unless you want the capture.
          </p>
        </div>
      )}
    </div>
  )
}
